<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.23">
  <POU Name="MAIN" Id="{4778274d-94da-4aca-b3f8-4cf5fa0c2e62}">
    <Declaration><![CDATA[
PROGRAM MAIN
VAR
    simIO : MNG_Simulation;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Update IOs with simulation
simIO(bEnable := TRUE);

// Application code follows here:


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>